"""update admin model

Revision ID: bb32ef46c1c2
Revises: 
Create Date: 2025-10-04 11:39:58.236212

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'bb32ef46c1c2'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admins', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_index(op.f('ix_admins_uid'), table_name='admins')
    op.create_index(op.f('ix_admins_uid'), 'admins', ['uid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_admins_uid'), table_name='admins')
    op.create_index(op.f('ix_admins_uid'), 'admins', ['uid'], unique=False)
    op.alter_column('admins', 'password_hash',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
